kind: pipeline
name: docker-build-and-push-to-dockerhub

steps:
- name: ads-service-fixed
  image: plugins/docker
  settings:
    dockerfile: ads-service-fixed/Dockerfile
    repo: ruanmarins96/ads-service-fixed
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
