kind: pipeline
name: docker-build-and-push-to-dockerhub

steps:
- name: ads-service-fixed
  image: plugins/docker
  settings:
    context: ads-service-fixed
    dockerfile: ads-service-fixed/Dockerfile
    repo: ruanmarins96/ads-service-fixed
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: store-frontend-instrumented-fixed
  image: plugins/docker
  settings:
    context: store-frontend-instrumented-fixed
    dockerfile: store-frontend-instrumented-fixed/Dockerfile
    repo: ruanmarins96/store-frontend-instrumented-fixed
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password

- name: discounts-service-fixed
  image: plugins/docker
  settings:
    context: discounts-service-fixed
    dockerfile: discounts-service-fixed/Dockerfile
    repo: ruanmarins96/discounts-service-fixed
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
